-- DDL skeleton cho BT1; cần được người học rà soát trước khi dùng trong BT2.
CREATE TABLE service_center (
    center_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_code VARCHAR(20) NOT NULL UNIQUE,
    center_name VARCHAR(120) NOT NULL
);

CREATE TABLE part (
    part_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    part_code VARCHAR(30) NOT NULL UNIQUE,
    part_name VARCHAR(120) NOT NULL,
    unit_price NUMERIC(12, 0) NOT NULL CHECK (unit_price >= 0)
);

CREATE TABLE employee (
    employee_id BIGINT PRIMARY KEY,
    center_id BIGINT NOT NULL REFERENCES service_center(center_id),
    role VARCHAR(20) NOT NULL CHECK (role IN ('KTV', 'QLTT')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE part_stock (
    center_id BIGINT NOT NULL REFERENCES service_center(center_id),
    part_id BIGINT NOT NULL REFERENCES part(part_id),
    quantity INTEGER NOT NULL DEFAULT 0 CHECK (quantity >= 0),
    min_threshold INTEGER CHECK (min_threshold IS NULL OR min_threshold >= 0),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (center_id, part_id)
);

CREATE TABLE ticket_part (
    ticket_code VARCHAR(20) NOT NULL,
    center_id BIGINT NOT NULL REFERENCES service_center(center_id),
    part_id BIGINT NOT NULL REFERENCES part(part_id),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ticket_code, center_id, part_id)
);

CREATE TABLE part_transaction (
    transaction_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    center_id BIGINT NOT NULL REFERENCES service_center(center_id),
    part_id BIGINT NOT NULL REFERENCES part(part_id),
    ticket_code VARCHAR(20),
    employee_id BIGINT NOT NULL REFERENCES employee(employee_id),
    type VARCHAR(10) NOT NULL CHECK (type IN ('NHAP', 'XUAT')),
    quantity INTEGER NOT NULL CHECK (quantity > 0),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    reference VARCHAR(80),
    CHECK ((type = 'NHAP' AND ticket_code IS NULL)
        OR (type = 'XUAT' AND ticket_code IS NOT NULL)),
    FOREIGN KEY (ticket_code, center_id, part_id)
        REFERENCES ticket_part(ticket_code, center_id, part_id)
);

CREATE INDEX idx_part_stock_alert
    ON part_stock (center_id, quantity, min_threshold);
CREATE INDEX idx_part_transaction_history
    ON part_transaction (center_id, part_id, occurred_at DESC);
CREATE INDEX idx_part_transaction_ticket
    ON part_transaction (ticket_code, center_id)
    WHERE ticket_code IS NOT NULL;

-- Khi xuất, service mở transaction, khóa dòng tồn bằng SELECT ... FOR UPDATE,
-- kiểm tra quantity >= số lượng yêu cầu, thêm ticket_part nếu cần, chèn ledger
-- XUAT, cập nhật part_stock rồi commit. Bất kỳ lỗi nào phải rollback toàn bộ.
